#!/bin/bash

exec docker run \
    --rm \
    --tty \
    --interactive \
    --device=/dev/net/tun \
    --name=openvpn-proxy-$(basename "$1") \
    --cap-add=NET_ADMIN \
    --publish 127.0.0.1:"$2":1080 \
    --volume "$(realpath "$1"):/etc/openvpn/:ro" \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --detach \
    mysocksproxy:latest
